apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexu

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secrets.yaml
  - nexu-api/deployment.yaml
  - nexu-api/service.yaml
  - nexu-web/deployment.yaml
  - nexu-web/service.yaml
  - gateway-pool/deployment.yaml
  - gateway-pool/service.yaml
  - gateway-pool/hpa.yaml
  - ingress/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
